### ISSUE TITLE
[BUG] "Cannot read properties of undefined (reading 'src)" error occurs when attempting to import pilot JSON file

### ISSUE THREAD

**Issue by CassieDingo** [Eranziel/foundryvtt-lancer#510]
**Describe the bug**

**To Reproduce**
1. Export a character JSON file from comp/con of a character containing either of the KTB/LONG RIM/WALLFLOWER LCP  assets.
2. Boot foundry with Lancer V 1.4.1 installed and as an active game world
3. After booting the system and world, create a new character sheet
4. Proceed to the RM-4//SYNC tab of the sheet. 
5. Attempt to import the character via either a share code or the Json importer itself
6. Observe that when attempting to import the character, the following error appears: Failed to update pilot, likely due to missing LCP data: Cannot read properties of undefined (reading 'src') 

**Expected behavior**
User it able to import character data without fault. 

**Screenshots**
![image](https://user-images.githubusercontent.com/123167034/213684129-e48f244e-ba95-4579-9835-4058741aa136.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Foundry version: 10.286
 - Lancer system version : 1.4.1

**Additional context**
N/A

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
CassieDingo#9058

**Comment by dodgepong** [comment]
Just to verify: you have imported the Wallflower/KTB/Long Rim LCPs into Foundry, correct?

**Comment by msprijatelj** [comment]
I see something similar to this too with both share codes and json imports:
![image](https://user-images.githubusercontent.com/44978587/213757224-37b0efdb-b851-44ca-a606-5ecfed3548e7.png)

"Folder" is undefined despite my pilot living in a folder.  Json import gets the pilot imported but not the mech.

**Comment by CassieDingo** [comment]
Apologies for the delay! I am on AEDT time so i am just waking up haha

I can confirm i do have Wallflower/KTB/Long Rim installed into Foundry that is correct. 
![image](https://user-images.githubusercontent.com/123167034/213821545-be2e192f-9a93-42ab-866a-3930f8a01603.png)

**Comment by CassieDingo** [comment]
> I see something similar to this too with both share codes and json imports: ![image](https://user-images.githubusercontent.com/44978587/213757224-37b0efdb-b851-44ca-a606-5ecfed3548e7.png)
> 
> "Folder" is undefined despite my pilot living in a folder. Both cases import the pilot but not the mech/deployables.
> 
> UPDATE: The pilot import is also incomplete; Triggers, Talents, Licences, and Core Bonuses make it, but not pilot gear, pilot LL, pilot name or dossier, etc.

Just to add on here as well we are seeing that with share codes as well
my initial description failed to mention that and wanted to clarify Share Codes 100% are having this behavior as well.

**Comment by Eranziel** [comment]
The folder error is also reported in #512 and is fixed for the next release.

Just to make sure I'm not missing something, are you still able to make the `Cannot read properties of undefined (reading 'src')` error occur? I haven't been able to reproduce that error and I don't see where that error could be coming from in the code, so if you have a pilot that causes it I'd like a copy of them for testing to see what is going wrong.

**Comment by CassieDingo** [comment]
> The folder error is also reported in #512 and is fixed for the next release.
> 
> Just to make sure I'm not missing something, are you still able to make the `Cannot read properties of undefined (reading 'src')` error occur? I haven't been able to reproduce that error and I don't see where that error could be coming from in the code, so if you have a pilot that causes it I'd like a copy of them for testing to see what is going wrong.


I'm still able to recreate this issue at this moment. This seems to be across multiple piltos as well that ive been attempting to import. All of these pilots were set up in CC as well.  I have a screenshot of the log below attached of this instance as well.

Pilots & share codes:
Sunspot: IZNZVX
TIGER: S337DX
SCREE: 7488VF

I've also attached download links for Sunspot and TIGERs json files here:
Sunspot: https://cdn.discordapp.com/attachments/147509719307780096/1066201264989425684/SUNSPOT1.json
TIGER: https://cdn.discordapp.com/attachments/147509719307780096/1066201265530486865/TIG3R.json


![image](https://user-images.githubusercontent.com/123167034/213842013-9844582c-bc72-42d2-804d-31b75b36b012.png)

**Comment by CassieDingo** [comment]
_**Quick Correction**_

it looks like this version of sunspot i attached above is having the folder error. However TIG3R is still experiencing it. Attached a screenshot of that specific use below.

![image](https://user-images.githubusercontent.com/123167034/213842338-c3ec4338-cc3b-4286-80e2-bb6e4ea5162e.png)

**Comment by Eranziel** [comment]
With the fix for #512 in place, TIG3R and your other pilots import successfully, so I'll mark this closed. Thanks for the help!

**Comment by CassieDingo** [comment]
Not a problem! Happy to help out always! 

Thank you for the rapid response and fix up for this issue as well! <3
