### ISSUE TITLE
[BUG] Cannot Add New Equipment/Traits to NPCs + Cannot

### ISSUE THREAD

**Issue by Warlynx** [Eranziel/foundryvtt-lancer#674]
**Describe the bug**
When I try to make some homebrew stuff, I cannot give any of my custom NPCs any traits, systems, weapons, or anything else to them, even ones that are on base-game NPCs. In addition, I cannot edit any pilot gear actions at all.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Foundry version: 11.315
 - Lancer system version: 2.0.4

**Discord contact info**
generic_lynx_username
(Should have a Catapult-J as the profile picture)

**Comment by Eranziel** [comment]
Actions aren't currently editable, see #634. In the future, please make separate issues for unrelated problems. I'm going to rename this issue to only refer to NPCs.

For the issues you're having with NPCs, please spell out exactly what steps you're doing, what goes wrong, and what you expected to happen. Screenshots would be great.

**Comment by Warlynx** [comment]
Thanks for reaching out to me, and appreciate the rename

For the steps I did when I encountered the NPC issues:
- 1: Make a new NPC weapon, system, or trait
- 2: Try to drag the created NPC equipment into either their class or template's base systems or optional systems
- 3: Whenever I release the item to 'drop' it in, it does not go in

![image](https://github.com/Eranziel/foundryvtt-lancer/assets/89091224/1ef3f0d2-9787-4023-bfc1-ff5429f70ce9)
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/89091224/13e8c349-78a6-46df-8725-bde1eadc7d3e)
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/89091224/f58e130d-ba23-4609-b526-c63ee0ea64f4)

**Comment by Warlynx** [comment]
Even after updating to Lancer Foundry 2.1.0 update, I still cannot add any equipment to npcs or templates

**Comment by Eranziel** [comment]
That would be because I haven't fixed it yet. ;) This issue will get a notification when a fix is added to the code.

**Comment by Eranziel** [comment]
I'm unable to replicate the issue on either Edge, Chrome, or Firefox.

Can you try with all modules disabled? If that still doesn't work, check whether you have a browser extension or something that's interfering? For example, by connecting with an incognito/private window.

**Comment by Alkyama** [comment]
I have managed to replicate it. All modules disabled.
Chrome 126.0.6478.56 
Windows 11
Foundry v11.135
Lancer VTT v2.1.0

Steps to replicate:
1. Create a NPC Feature on a new compendium.
2. Create a NPC Class on the same compendium.
3. Drag NPC Feature to either Base Features or Optional Features.
4. No feature is added.

Bonus:
If the NPC feature was created from a duplicate from an original feature, it will display the original feature's details, instead of the new ones that have been edited in.

![image](https://github.com/Eranziel/foundryvtt-lancer/assets/25304929/ae827d05-072c-4d79-9ee8-c843b9adeec6)
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/25304929/cf125e57-d8be-4376-ab06-4dd4cefb1151)
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/25304929/a65ab42b-f360-4a80-bf97-d8113b2dd9dc)

**Comment by Eranziel** [comment]
I see. That sounds like a side effect of editing them inside the compendium. I'll look into a solution when I have time, but the simple workaround for now would be to work on the class/template outside the compendium (i.e. in the Items tab), then move it back into the compendium when you're finished.

**Comment by Alkyama** [comment]
Also, this is only affecting NPC Classes on the Compendium. I've managed to use these compendium created NPC features on NPC Sheets on the Actors tab.

**Comment by Alkyama** [comment]
I have confirmed this problem happens to NPC Classes on the Item tab as well. I tried creating new NPC Features and drag it to a new NPC Class and it didn't work either.

**Comment by SirKostya** [comment]
I have managed to manually fix this issue by adding appropriate lid in an items json file and then importing it back. This seems to be related to both the problem with adding new items as well as copies of items working incorrectly, as npc class uses "lid" of npc features for their "base_features", and an empty "lid" (on a newly created item) or an impoprted "lid" (from a copy) doesn't add properly.

**Comment by SirKostya** [comment]
Newly created npc feature in items tab
![изображение](https://github.com/Eranziel/foundryvtt-lancer/assets/128192291/08a6a50b-c75b-4665-a31c-0f56b07c155b)
Newly created npc class after attempting (and failing) to add the feature
![изображение](https://github.com/Eranziel/foundryvtt-lancer/assets/128192291/4a0bf54e-d92f-4f0e-b86c-5039909e779f)
Npc feature after manually adding a lid
![изображение](https://github.com/Eranziel/foundryvtt-lancer/assets/128192291/071e8cc7-2459-4625-bf6c-4a4890fd4d29)
Works as intended
![изображение](https://github.com/Eranziel/foundryvtt-lancer/assets/128192291/d14a0dde-f66c-486b-b5c5-cd10106a7b1e)
Npc class after adding an npc feature with a lid
![изображение](https://github.com/Eranziel/foundryvtt-lancer/assets/128192291/5e2ec6fa-69bf-4bc2-bc66-e2b54b3c0fb0)

**Comment by SirKostya** [comment]
If an item with the same lid already exists in a compendium it will replace the feature (Test_feature in this example) with the one from compendium.
![изображение](https://github.com/Eranziel/foundryvtt-lancer/assets/128192291/fe3f7ac2-b6cf-4099-ae4e-aa0c4054f1ae)
![изображение](https://github.com/Eranziel/foundryvtt-lancer/assets/128192291/07879ab0-578e-4880-9bdc-33e91b340680)

**Comment by Eranziel** [comment]
@SirKostya @Alkyama please give it a try on Lancer 2.1.4 when you get a chance. I'm not 100% sure the problem is solved, since I wasn't able to reliably replicate it. Thanks for the detailed reports, though!

**Comment by SirKostya** [comment]
Issue is fixed for newly created items but not for copies.
Adding a newly created feature without any modifications works as intended.
![изображение](https://github.com/Eranziel/foundryvtt-lancer/assets/128192291/d4d53f4d-8b64-4039-8551-060470a47a0a)z
In-file lid remains unchanged for features
![изображение](https://github.com/Eranziel/foundryvtt-lancer/assets/128192291/882d4423-be46-4c78-b0c5-98573b7702cd)
But appears as id in classes
![изображение](https://github.com/Eranziel/foundryvtt-lancer/assets/128192291/0128584e-d544-4a9b-82f7-08b2e869694f)
A bug with items copied from compendium working incorrectly (see my comment above) still persists, but I assume this would have to be opened as a separate Issue.

**Comment by Eranziel** [comment]
That's fine, we can keep this issue open for that. I've got an idea for a fix, I'll try to include it in the next release.

**Comment by Alkyama** [comment]
Newly created itens created on the item tab seems to be working fine. If you try that with NPC Classes / Templates and/or NPC Features created on the Compendium tab, we're still seeing some errors about missing LCPs for them.
